version: '3.8'

services:
  db:
    image: postgres:10
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'aaaaaaaaaaaaaaaaaaa'
        POSTGRES_USER: 'postgres'
        POSTGRES_HOST_AUTH_METHOD: 'md5'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 7432:5432

  ctcexploder:
    depends_on:
      - db
    image: registry.cn-hangzhou.aliyuncs.com/ctexploder/ctcexploder:${DOCKER_TAG:-latest}
    restart: always
    container_name: 'ctcexploder'
    links:
      - db:database
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'github.com:140.82.113.4'
      - 'github.global.ssl.fastly.net:199.232.69.194'
    env_file:
      -  ./envs/common-blockscout.env
    environment:
        ETHEREUM_JSONRPC_VARIANT: 'geth'
        BLOCK_TRANSFORMER: 'clique'
        DATABASE_URL: postgresql://postgres:aaaaaaaaaaaaaaaaaaa@host.docker.internal:7432/ct_exploder_pgsql_v3?ssl=false
        ECTO_USE_SSL: false
        ETHEREUM_JSONRPC_HTTP_URL: http://182.43.26.165:7401/
        COIN: CT
        SUBNETWORK: 草田
        NETWORK: 链
        COINGECKO_COIN_ID: usd-coin
        DISABLE_READ_API: false
        DISABLE_WEBAPP: false
        ADMIN_PANEL_ENABLED: true
        WOBSERVER_ENABLED: true
        APPS_MENU: true
        EXTERNAL_APPS: "[{\"url\":\"https://wallet.ctblock.cn/\",\"title\":\"链上工具\"},{\"url\":\"https://ctblock.cn/chain_doc.html\",\"title\":\"节点安装\"}]"
        PORT: 4000
        BLOCKSCOUT_HOST: ctblock.cn
        HIDE_BLOCK_MINER: true
        MIX_ENV: prod
        HEX_HTTP_CONCURRENCY: 1
        HEX_HTTP_TIMEOUT: 120
        LOGO: /images/blockchainbrowser.png
        LOGO_FOOTER: /images/blockchainbrowser.png

    ports:
      - 4001:4001
      - 4000:4000

